src/objects/ContextType__mdt.object
<CustomObject>
    <description>Defines a context type, which is mapped to an object type</description>
    <label>Context Type</label>
    <pluralLabel>Context Types</pluralLabel>
</CustomObject>

src/objects/MeetingWorkFlowConfiguration__mdt.object
<CustomObject>
    <description>Defines the path the workflow will follow by using a controlling field to determine the steps.</description>
    <fields>
        <fullName>ContextType__c</fullName>
        <description>The Context Type that defines a relationship of the workflow record to an sObject type.</description>
        <inlineHelpText>The Context Type that defines a relationship of the workflow record to an sObject type.</inlineHelpText>
        <label>Context Type</label>
        <referenceTo>ContextType__mdt</referenceTo>
        <relationshipLabel>Workflow Paths</relationshipLabel>
        <relationshipName>WorkflowPaths</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>ControllingField__c</fullName>
        <description>The Context Type sObject picklist field name to define the path steps.</description>
        <inlineHelpText>The Context Type sObject picklist field name to define the path steps.</inlineHelpText>
        <label>Controlling Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingRecordTypeName__c</fullName>
        <caseSensitive>true</caseSensitive>
        <description>The name of the sObject Record Type that the workflow is configured for.</description>
        <inlineHelpText>The name of the sObject Record Type that the workflow is configured for.</inlineHelpText>
        <label>Record Type Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Workflow Path.</description>
        <inlineHelpText>The status of the Workflow Path.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Workflow Path</label>
    <pluralLabel>Workflow Paths</pluralLabel>
</CustomObject>

src/classes/WorkflowPathsListViewController.cls
public with sharing class WorkflowPathsListViewController {

    private static final String PATH_STATUS_ACTIVE = 'Active';
    private static final String DASH_SEPARATOR = '-';
    private static final String DEPLOYMENT_STATUS_DEPLOYED = 'Deployed';

    @TestVisible
    private static MeetingWorkFlowConfigurationDao meetingPathDao = new MeetingWorkFlowConfigurationDao();

    @AuraEnabled
    public static WorkflowPaths getWorkflowPaths() {
        try {
            List<MeetingWorkFlowConfiguration__mdt> configurations = meetingPathDao.getAllWithContextType();

            List<WorkflowPath> paths = new List<WorkflowPath>();
            for (MeetingWorkFlowConfiguration__mdt configuration : configurations) {
                paths.add(new WorkflowPath(configuration));
            }

            return new WorkflowPaths(paths);
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

    public class WorkflowPaths {

        @AuraEnabled
        public List<WorkflowPath> paths = new List<WorkflowPath>();

        @AuraEnabled
        public String namespace = PackageUtilities.namespace;

        public WorkflowPaths(List<WorkflowPath> paths) {
            this.paths = paths;
        }
    }

    public class WorkflowPath {

        @AuraEnabled
        public Id id;

        @AuraEnabled
        public String developerName;

        @AuraEnabled
        public String label;

        @AuraEnabled
        public String contextType;

        @AuraEnabled
        public String recordTypeName;

        @AuraEnabled
        public String controllingField;

        @AuraEnabled
        public String activeStatus;

        @AuraEnabled
        public String deploymentStatus;

        public WorkflowPath(MeetingWorkFlowConfiguration__mdt configuration) {
            this.id = configuration.Id;
            this.developerName = configuration.DeveloperName;
            this.label = configuration.MasterLabel;
            this.contextType = configuration.ContextType__r.MasterLabel;
            this.recordTypeName = this.formatRecordTypeName(configuration.MeetingRecordTypeName__c);
            this.controllingField = configuration.ControllingField__c;
            this.activeStatus = configuration.Status__c;
            this.deploymentStatus = DEPLOYMENT_STATUS_DEPLOYED;
        }

        private String formatRecordTypeName(String name) {
            if (String.isEmpty(name) || !name.contains(DASH_SEPARATOR)) return name;
            return name.substringAfter(DASH_SEPARATOR);
        }
    }
}