src/objects/ContextType__mdt.object
<CustomObject>
    <description>Defines a context type, which is mapped to an object type</description>
    <label>Context Type</label>
    <pluralLabel>Context Types</pluralLabel>
</CustomObject>

src/objects/MeetingWorkFlowConfiguration__mdt.object
<CustomObject>
    <description>Defines the path the workflow will follow by using a controlling field to determine the steps.</description>
    <fields>
        <fullName>ContextType__c</fullName>
        <description>The Context Type that defines a relationship of the workflow record to an sObject type.</description>
        <inlineHelpText>The Context Type that defines a relationship of the workflow record to an sObject type.</inlineHelpText>
        <label>Context Type</label>
        <referenceTo>ContextType__mdt</referenceTo>
        <relationshipLabel>Workflow Paths</relationshipLabel>
        <relationshipName>WorkflowPaths</relationshipName>
        <type>MetadataRelationship</type>
    </fields>
    <fields>
        <fullName>ControllingField__c</fullName>
        <description>The Context Type sObject picklist field name to define the path steps.</description>
        <inlineHelpText>The Context Type sObject picklist field name to define the path steps.</inlineHelpText>
        <label>Controlling Field</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <description>The status of the Workflow Path.</description>
        <inlineHelpText>The status of the Workflow Path.</inlineHelpText>
        <label>Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Active</fullName>
                    <default>true</default>
                    <label>Active</label>
                </value>
                <value>
                    <fullName>Inactive</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <label>Workflow Path</label>
    <pluralLabel>Workflow Paths</pluralLabel>
</CustomObject>

src/objects/MeetingWorkFlowNodeConfiguration__mdt.object
<CustomObject>
    <description>Defines a step in the workflow.</description>
    <fields>
        <fullName>MeetingStatus__c</fullName>
        <description>Values related to the Workflow Path Controlling Field.</description>
        <inlineHelpText>Values related to the Workflow Path Controlling Field.</inlineHelpText>
        <label>Controlling Field Values</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MeetingWorkFlowConfiguration__c</fullName>
        <description>The Workflow Path definition.</description>
        <inlineHelpText>The Workflow Path definition.</inlineHelpText>
        <label>Workflow Path</label>
        <referenceTo>MeetingWorkFlowConfiguration__mdt</referenceTo>
        <relationshipLabel>Workflow Path Nodes</relationshipLabel>
        <relationshipName>MeetingWorkFlowNodeConfigurations</relationshipName>
        <required>true</required>
        <type>MetadataRelationship</type>
    </fields>
    <label>Workflow Path Node</label>
    <pluralLabel>Workflow Path Nodes</pluralLabel>
</CustomObject>

src/classes/WorkflowPath.cls
public inherited sharing class WorkflowPath {
    private static final String ACTIVE_STATUS = 'Active';
    private static final String MEETING_OBJECT_NAME = SObjectType.Meeting__c.getName();
    private static final String MEETING_STATUS_FIELD_NAME = SObjectType.Meeting__c.fields.Status__c.getName();

    @AuraEnabled
    public String id { private get; private set; }
    @AuraEnabled
    public String label { private get; private set; }
    @AuraEnabled
    public String name { private get; private set; }
    @AuraEnabled
    public String controllingField { private get; private set; }
    @AuraEnabled
    public String status { private get; private set; }
    @AuraEnabled
    public String recordType { private get; private set; }
    @AuraEnabled
    public String objectName { private get; private set; }
    @AuraEnabled
    public ContextType__mdt contextType { private get; private set; }
    @AuraEnabled
    public List<WorkflowPathNode> nodes { private get; private set; }

    private MeetingWorkFlowConfiguration__mdt record;
    private WorkflowPathObjectRecordType objectRecordType;

    public WorkflowPath(MeetingWorkFlowConfiguration__mdt workflow) {
        this.record = workflow;
        this.objectRecordType = WorkflowPathObjectRecordType.byUsing(workflow);

        this.id = workflow.Id;
        this.label = workflow.MasterLabel;
        this.name = workflow.DeveloperName;
        this.status = workflow.Status__c;
        this.recordType = this.objectRecordType.getRecordType();
        this.objectName = this.objectRecordType.getObjectName();
        this.contextType = this.getContextType(workflow);
        this.controllingField = this.createControllingField(workflow);
        this.nodes = this.createWorkflowPathNodes(workflow);
    }

    public Id getId() {
        return this.id;
    }

    public String getLabel() {
        return this.label;
    }

    public String getName() {
        return this.name;
    }

    public String getControllingField() {
        return this.controllingField;
    }

    public String getStatus() {
        return this.status;
    }

    public String getRecordType() {
        return this.recordType;
    }

    public String getObjectName() {
        return this.objectName;
    }

    public ContextType__mdt getContextType() {
        return this.contextType;
    }

    public List<WorkflowPathNode> getNodes() {
        return this.nodes;
    }

    public WorkflowPathObjectRecordType getObjectRecordType() {
        return this.objectRecordType;
    }

    public Boolean isLegacy() {
        return this.contextType == null;
    }

    public Boolean isActive() {
        return this.status == ACTIVE_STATUS;
    }


    private List<WorkflowPathNode> createWorkflowPathNodes(MeetingWorkFlowConfiguration__mdt workflow) {
        List<WorkflowPathNode> nodes = new List<WorkflowPathNode>();

        for(String picklistOption : ObjectUtilities.getActivePicklistValues(objectName, controllingField)){
            for (MeetingWorkFlowNodeConfiguration__mdt nodeMdt : workflow.MeetingWorkFlowNodeConfigurations__r) {
                if(nodeMdt.MeetingStatus__c == picklistOption){
                    nodes.add(new WorkflowPathNode(nodeMdt));
                }
            }
        }

        return nodes;
    }

    private String createControllingField(MeetingWorkFlowConfiguration__mdt workflow) {
        return this.isLegacy() ? MEETING_STATUS_FIELD_NAME : workflow.ControllingField__c;
    }

    private ContextType__mdt getContextType(MeetingWorkFlowConfiguration__mdt workflow) {
        return JSON.serialize(workflow).contains('ContextType__r') ? workflow.ContextType__r : null;
    }
}